SELECT * FROM almacen.CNVLROLUSU;

use almacen 

-- Catálogo de niveles de roles de usuarios
CREATE TABLE CNVLROLUSU(
  NIDNVL   INTEGER(3),   -- Clave del nivel de rol de usuario
  DESCTIPNVL  VARCHAR(18) -- Descripción del tipo de rol de usuario
  );
  
ALTER TABLE CNVLROLUSU ADD CONSTRAINT PK_CNVLROLUSU
  PRIMARY KEY  (NIDNVL);
  
ALTER TABLE `almacen`.`tususis` 
ADD COLUMN `NIDNVL` INTEGER(3) NULL DEFAULT NULL AFTER `CVIGENT`;
  
ALTER TABLE TUSUSIS ADD CONSTRAINT FK_TUSUSIS_CNVLROLUSU 
  FOREIGN KEY (NIDNVL) REFERENCES CNVLROLUSU (NIDNVL);
  
INSERT INTO `almacen`.`CNVLROLUSU` (`NIDNVL`, `DESCTIPNVL`) VALUES ('1', 'Master');
INSERT INTO `almacen`.`CNVLROLUSU` (`NIDNVL`, `DESCTIPNVL`) VALUES ('2', 'Administrador Principal');
INSERT INTO `almacen`.`CNVLROLUSU` (`NIDNVL`, `DESCTIPNVL`) VALUES ('3', 'Administrador Secundario');
INSERT INTO `almacen`.`CNVLROLUSU` (`NIDNVL`, `DESCTIPNVL`) VALUES ('4', 'Usuario');
INSERT INTO `almacen`.`CNVLROLUSU` (`NIDNVL`, `DESCTIPNVL`) VALUES ('5', 'Pendiente');