  CCVEUSU  VARCHAR(10),  -- Clave de usuario
  CPASSWR  VARCHAR(20),   -- Password
  CNOMBRE VARCHAR(35), -- Nombre(s) del usuario
  CPRIAPE    VARCHAR(35),   -- Primer apellido
  CSEGAPE    VARCHAR(35),   -- Segundo apellido
  NIDAREA   INTEGER(3),  -- ID del área
  CVIGENT  CHAR(1));    -- Indica si el registro se encuentra S=Vigente o N=No vigente
  
  insert into TUSUSIS values ()
  
DJARAMILLOV	JARAMILLO	VIGUERAS	DAVID  ADMINISTRADOR	SA01JVD2021 
JPÉREZX	PÉREZ	X	JORGE	ADMINISTRADOR	SA02PXJ2021
FTAGLEC	TAGLE 	CONTRERAS	FRANCISCO JAVIER	ADMINISTRADOR	SA03TCF2021
CMATAMOROSL	MATAMOROS	LARA	CLAUDIO	ADMINISTRADOR	SA04MLC2021
FCERDAM	CERDA	MARTÍNEZ	FRANCISCO JAVIER	ADMINISTRADOR	SA05CMF2021
CORDOÑESL	ORDOÑES	LÓPEZ 	CRISÓFORO	ADMINISTRADOR	SA06OLC2021
HCASTILLOF	CASTILLO	FERNÁNDEZ	HUGO	ADMINISTRADOR	SA07CFH2021
VSALAZARS	SALAZAR	SÁNCHEZ	VIDAL	ADMINISTRADOR	SA08SSV2021
ÁALVARADOH	ALVARADO	HERNÁNDEZ	ÁLVARO	USUARIO	SA09AHÁ2021
EÁLVAREZH	ÁLVAREZ 	HERNÁNDEZ 	EDITH	ADMINISTRADOR	SA10ÁHE2021
JALVARADOM	ALVARADO 	MERCADO 	JOSE ARTURO	PENDIENTE	SA11AMJ2021
MAVIÑAM	AVIÑA 	MEDINA	MATILDE CELINA	USUARIO	SA12AMM2021
ABAEZAO	BAEZA 	ORDUÑA 	ARACELI	USUARIO	SA13BOA2021
NBOBADILLAV	BOBADILLA	VIRAMONTES	NORMA ESTELA	USUARIO	SA14BVN2021
MGARCIAR	GARCIA 	RODRIGUEZ 	MARGARITA	USUARIO	SA15GRM2021
EGODINEZR	GODINEZ 	RODRIGUEZ 	ERNESTO	USUARIO	SA16GRE2021
LGÓMEZL	GÓMEZ 	LÓPEZ 	LAURA PATRICIA	USUARIO	SA17GLL2021
SGONZÁLEZG	GONZÁLEZ 	GOVEA 	SERGIO	USUARIO	SA18GGS2021
LHERNÁNDEZT	HERNÁNDEZ 	TINAJERO 	LAURA	USUARIO	SA19HTL2021
ENATERASM	NATERAS 	MOLINA 	EDUARDO	USUARIO	SA20NME2021
VMORFÍNS	MORFÍN 	SILVA 	VIRGINIA	USUARIO	SA21MSV2021
CORDORICAV	ORDORICA	VARGAS	CARLOS	USUARIO	SA22OVC2021
CPINOF	PINO 	FONSECA 	CLAUDIA YADIRA	USUARIO	SA23PFC2021
EPIÑAO	PIÑA 	OSCOY	EDGAR	USUARIO	SA24POE2021
ASANCHEZB	SANCHEZ 	BORDES	ALEJANDRO GUADALUPE	USUARIO	SA25SBA2021
VTOLEDOS	TOLEDO 	SIERRA 	VICENTE 	USUARIO	SA26TSV2021
AVARGASC	VARGAS 	CASAS 	AGUSTIN	ADMINISTRADOR	SA27VCA2021
ASÁNCHEZF	SÁNCHEZ	FRAGOSO	ANTONIO	ADMINISTRADOR	SA66SFA2021
MALVAREZZ	ALVAREZ 	ZAMORA 	MARIA DEL CONSUELO	USUARIO	SA28AZM2021
PCARRILLOC	CARRILLO 	CERDA 	PAOLA AURORA	USUARIO	SA29CCP2021
ZCASTELLANOSP	CASTELLANOS 	PEREZ 	ZOILA	USUARIO	SA30CPZ2021
MCASABT	CASAB 	TAVARES 	MARTHA GENOVEVA	USUARIO	SA31CTM2021
ECRUZS	CRUZ 	SANTIAGO	ELIZABETH	USUARIO	SA32CSE2021
GDÍAZL	DÍAZ	LUGO	GLADIS GABRIELA	USUARIO	SA33DLG2021
FENRIQUEZS	ENRIQUEZ 	SEGURA 	FERNANDO	USUARIO	SA34ESF2021
EGARCIAL	GARCIA 	LOPEZ 	ELVIA TERESA	ADMINISTRADOR	SA35GLE2021
LGRANADOSL	GRANADOS 	LÓPEZ 	LAURA ELVIRA	USUARIO	SA36GLL2021
MGARCÍAN	GARCÍA	NORIEGA 	MARTHA ISABEL	USUARIO	SA37GNM2021
MGARCIAV	GARCIA 	VIDRIO 	MARGARITA	USUARIO	SA38GVM2021
CGOMEZF	GOMEZ 	FLORES 	CLAUDIA	USUARIO	SA39GFC2021
PHERNANDEZM	HERNANDEZ 	MORENO 	PATZY	USUARIO	SA40HMP2021
AISLASC	ISLAS 	CORTES 	ANA ALEJANDRA	ADMINISTRADOR	SA41ICA2021
DJIMENEZS	JIMENEZ 	SANCHEZ	DANIELA	USUARIO	SA42JSD2021
LJIMENEZS	JIMENEZ 	SORIA 	LUIS	USUARIO	SA43JSL2021
CLAYSECAR	LAYSECA 	RODRIGUEZ 	CATALINA	USUARIO	SA44LRC2021
ÁLIRAM	LIRA 	MACIAS	ÁNGEL ABRAHAM	USUARIO	SA45LMÁ2021
DMARQUEZC	MARQUEZ 	CUEVAS 	DEBORAH ITZAYANA	USUARIO	SA46MCD2021
MMAGALLONM	MAGALLON 	MARTINEZ 	MARTHA CITLALI	USUARIO	SA47MMM2021
RMEDINAR	MEDINA 	REYES 	ROSA GEORGINA	USUARIO	SA48MRR2021
JMARTÍNEZV	MARTÍNEZ	VÁLDEZ	JAVIER EDGARDO	MASTER	SA49MVJ2021
IMEJIAM	MEJIA 	MARTINEZ	ISABEL CRISTINA	USUARIO	SA50MMI2021
VMUNGUÍAU	MUNGUÍA 	URIBE 	VERÓNICA ALEJANDRA	USUARIO	SA51MUV2021
APEREZM	PEREZ 	MORENO 	AMALIA	USUARIO	SA52PMA2021
JRAMIREZM	RAMIREZ 	MUNGUIA 	JESUS MARTIN	ADMINISTRADOR	SA53RMJ2021
LREGALADON	REGALADO 	NIETO 	LETICIA	USUARIO	SA54RNL2021
LRODRÍGUEZJ	RODRÍGUEZ	JIMÉNEZ 	LETICIA	ADMINISTRADOR	SA55RJL2021
PRIVASL	RIVAS 	LÓPEZ 	PATRICIA DENISSE	USUARIO	SA56RLP2021
JRUÍZV	RUÍZ 	VERA 	JUAN CARLOS	USUARIO	SA57RVJ2021
JSANDOVALM	SANDOVAL 	MEDINA 	JUAN ANTONIO	USUARIO	SA58SMJ2021
MVÁZQUEZL	VÁZQUEZ 	LIRA	MARGARITA	USUARIO	SA59VLM2021
VRODRÍGUEZR	RODRÍGUEZ	RAMÍREZ	VERÓNICA	USUARIO	SA60RRV2021
RDURÓNF	DURÓN	FIERRO	RAÚL	USUARIO	SA67DFR2021
LAGUILARP	AGUILAR	PÉREZ	LUIS ANTONIO	USUARIO	SA61APL2021
DDEMSD	DEMS	DEMS	DEMS	ADMINISTRADOR	SA62DDD2021
DDESD	DES	DES	DES	ADMINISTRADOR	SA63DDD2021
DDFLED	DFLE	DFLE	DFLE	ADMINISTRADOR	SA64DDD2021
DDFIED	DFIE	DFIE	DFIE	PENDIENTE	SA65DDD2021